// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://souugenqskkdgwaladjz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNvdXVnZW5xc2trZGd3YWxhZGp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzNTI0NjEsImV4cCI6MjA2MTkyODQ2MX0.brYuLwwvxyEdf87fRaSpQxDWzE189VsFgaAOn97hK8w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);